# -*- coding: utf-8 -*-
"""TP1_EJ2_PDI.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1WtEkvypFiQ6mi6Hn57z5xz_9-wsK3bA4
"""

import cv2
import numpy as np
import pandas as pd
import os
import re

# =========================================================================
# 1. CONSTANTES GLOBALES Y UMBRALES
# =========================================================================
ARCHIVOS_FORMULARIO = [f'formulario_0{i}.png' for i in range(1, 6)]
CAMPO_NOMBRES = [
    "Nombre y Apellido", "Edad", "Mail", "Legajo",
    "Pregunta 1", "Pregunta 2", "Pregunta 3", "Comentarios"
]
CSV_OUTPUT = 'validacion_resultados_final.csv'

# UMBRALES DE PREPROCESAMIENTO Y FILTRADO INICIAL
MIN_CHAR_AREA = 10

# UMBRALES DE VALIDACIÓN CRÍTICOS (Ajustados para los requisitos)
MIN_CC_MARCA = 2  # CC mínimo para considerar una casilla de Si/No como 'marcada'
MAX_CC_RUIDO = 2  # CC máximo permitido en una casilla NO marcada (tolerancia al ruido)

# UMBRALES PARA EL FILTRO ESTRUCTURAL
MAX_RELACION_ASPECTO = 8.0  # Para descartar líneas delgadas y ruido estructural
MIN_DIMENSION_CARACTER = 5  # Dimensión mínima para analizar Aspect Ratio
# Estos ya no son tan críticos si usamos el conteo de CC, pero se mantienen para debug:
ANCHO_PROMEDIO_CARACTER = 8
ANCHO_PROMEDIO_PALABRA = 50

# Lista de campos donde se aplica la EROSIÓN AGRESIVA en el Formulario 03
CAMPOS_ERODIR_FORM03 = ["Nombre y Apellido", "Edad", "Mail", "Legajo", "Pregunta 1", "Pregunta 2", "Pregunta 3", "Comentarios"]

# =========================================================================
# 2. DETECCIÓN DE COORDENADAS (Se mantiene la lógica original)
# =========================================================================

def detectar_coordenadas_campos(img_gray):
    H, W = img_gray.shape

    _, img_th = cv2.threshold(img_gray, 200, 255, cv2.THRESH_BINARY_INV)
    img_rows = np.sum(img_th, axis=1)
    th_row = np.max(img_rows) * 0.7
    line_row_th = img_rows > th_row

    def encontrar_posiciones_lineas(line_th):
        posiciones = []
        in_line = False
        start = -1
        for i, val in enumerate(line_th):
            if val and not in_line:
                start = i
                in_line = True
            elif not val and in_line:
                # Se utiliza el punto medio
                posiciones.append((start + i) // 2)
                in_line = False
        return sorted(list(set(posiciones)))

    h_coords = encontrar_posiciones_lineas(line_row_th)

    UMBRAL_Y_MIN = H * 0.08
    y_lines_detectadas = sorted([y for y in h_coords if y > UMBRAL_Y_MIN])

    if len(y_lines_detectadas) < 9:
        y_lines = [int(H * (0.1 + i * 0.09)) for i in range(9)]
    else:
        y_lines = y_lines_detectadas[:9]

    img_cols = np.sum(img_th, axis=0)
    th_col = np.max(img_cols) * 0.6
    line_col_th = img_cols > th_col
    v_coords = encontrar_posiciones_lineas(line_col_th)

    MIN_COORD_X = W * 0.05
    x_lines_filtradas = sorted([x for x in v_coords if x > MIN_COORD_X])

    if len(x_lines_filtradas) >= 4:
        x_lines = x_lines_filtradas[:4]
    else:
        x_lines = [int(W * 0.035), int(W * 0.335), int(W * 0.658), int(W * 0.975)]

    celdas_data = []

    DESPLAZAMIENTO_Y = 41
    h_row_p_std = y_lines[6] - y_lines[5]
    y_end_p3_fixed = y_lines[6] + h_row_p_std + DESPLAZAMIENTO_Y
    y_start_comentarios = y_end_p3_fixed + 10

    x_start_label = x_lines[0]
    x_start_data = x_lines[1] + 4
    x_start_si = x_lines[1] + 4
    x_start_no = x_lines[2]
    x_end_data = x_lines[-1] - 33

    # --- INICIO DEL CÓDIGO MODIFICADO ---
    # Constante para crear un margen y evitar que la línea divisoria central solape
    X_AJUSTE_CENTRAL = 3

    # Coordenada final para 'Si' (justo antes de la línea central)
    x_end_si_ajustado = x_start_no - X_AJUSTE_CENTRAL

    # Coordenada inicial para 'No' (justo después de la línea central)
    x_start_no_ajustado = x_start_no + X_AJUSTE_CENTRAL
    # --- FIN DEL CÓDIGO MODIFICADO ---

    for i in range(len(CAMPO_NOMBRES)):
        campo_nombre = CAMPO_NOMBRES[i]
        y_start = y_lines[i]

        if i < 7:
            y_end = y_lines[i+1]

            if i >= 4:
                y_start += DESPLAZAMIENTO_Y
                y_end += DESPLAZAMIENTO_Y
                if i == 6: y_end = y_end_p3_fixed

            if i < 4:
                # Texto (Nombre, Legajo, etc.): Solo columna de datos
                celdas_data.append(((y_start, y_end, x_start_data, x_end_data), campo_nombre))

            elif i >= 4 and i <= 6:
                # Casillas Si/No
                p_id = i - 3

                # CASILLA SÍ (Usa la coordenada ajustada)
                celdas_data.append(((y_start, y_end, x_start_si, x_end_si_ajustado), f"P{p_id}_Si"))

                # CASILLA NO (Usa la coordenada ajustada)
                celdas_data.append(((y_start, y_end, x_start_no_ajustado, x_end_data), f"P{p_id}_No"))

        elif i == 7:
            y_start = y_start_comentarios - 7
            y_end = int(H * 0.95)
            # Comentarios: Solo columna de datos
            celdas_data.append(((y_start, y_end, x_start_data, x_end_data), campo_nombre))

    return celdas_data



# =========================================================================
# 3. FUNCIÓN DE EXTRACCIÓN (CON EROSIÓN CONDICIONAL Y FILTRO DE DIMENSIÓN)
# =========================================================================


def extraer_contenido_celda(img_gray, coords, file_id, campo_nombre):

    is_check_box = campo_nombre.startswith('P') and ('Si' in campo_nombre or 'No' in campo_nombre)


    y1, y2, x1, x2 = coords
    celda_img = img_gray[y1:y2, x1:x2]

    h_celda, w_celda = celda_img.shape[:2]

    celda_img_procesada = celda_img

    # --- LÓGICA CONDICIONAL DE EROSIÓN AGRESIVA (SOLO FORMULARIO 04 Y CAMPOS ESPECÍFICOS) ---
    if file_id == ['01','04'] and campo_nombre in CAMPOS_ERODIR_FORM03:
        # La impresión de debug es útil para ver si el filtro se aplica
        # print(f"  [DEBUG] 💥 Aplicando Erosión Agresiva (x2) a {campo_nombre} (Formulario 03)")
        kernel = np.ones((3,3), np.uint8)
        celda_img_procesada = cv2.erode(celda_img, kernel, iterations=2)

    # --- PREPROCESAMIENTO GENERAL ---
    kernel_laplace = np.array([[-1, -1, -1], [-1, 9, -1], [-1, -1, -1]], dtype=np.float32)
    celda_boost = cv2.filter2D(celda_img_procesada, -1, kernel_laplace)
    celda_boost = np.clip(celda_boost, 0, 255).astype(np.uint8)
    celda_filtered = cv2.medianBlur(celda_boost, 3)
    celda_contrast = cv2.equalizeHist(celda_filtered)

    # Umbral
    _, celda_th = cv2.threshold(celda_contrast, 0, 255, cv2.THRESH_BINARY_INV | cv2.THRESH_OTSU)

    # Detección de Componentes Conexos
    num_labels, labels, stats, centroids = cv2.connectedComponentsWithStats(celda_th, 8, cv2.CV_32S)

    stats_filtrados_final = np.array([])
    num_componentes = 0

    if num_labels > 1:
        stats = stats[1:, :]

        # 1. Filtro por Área Mínima (descartar ruido muy pequeño)
        ix_area = stats[:, cv2.CC_STAT_AREA] > MIN_CHAR_AREA
        stats_filtrados = stats[ix_area, :]

        # --- FILTRO ESTRUCTURAL AVANZADO (Dimensiones Máximas y Aspecto) ---
        IX_W = cv2.CC_STAT_WIDTH
        IX_H = cv2.CC_STAT_HEIGHT
        ix_estructura = np.ones(len(stats_filtrados), dtype=bool)

        for i, stat in enumerate(stats_filtrados):
            w = stat[IX_W]; h = stat[IX_H]

            # Filtro 1: Descartar CCs que ocupan casi todo el ancho/alto (Líneas residuales)
            if w >= w_celda * 0.95 or h >= h_celda * 0.95:
                ix_estructura[i] = False
                continue

            # Filtro 2: Descartar formas muy alargadas (Relación de Aspecto)
            if w >= MIN_DIMENSION_CARACTER and h >= MIN_DIMENSION_CARACTER:
                aspect_ratio_w_h = w / h
                aspect_ratio_h_w = h / w
                if aspect_ratio_w_h > MAX_RELACION_ASPECTO or aspect_ratio_h_w > MAX_RELACION_ASPECTO:
                    ix_estructura[i] = False

        stats_filtrados_final = stats_filtrados[ix_estructura, :]
        num_componentes = len(stats_filtrados_final)

    # --- ESTIMACIÓN DE CARACTERES Y PALABRAS ---
    num_caracteres_estimado = 0
    num_palabras_estimado = 0

    if num_componentes > 0:
        total_bbox_width = np.sum(stats_filtrados_final[:, cv2.CC_STAT_WIDTH])
        num_caracteres_estimado = int(total_bbox_width / ANCHO_PROMEDIO_CARACTER)
        num_palabras_estimado = int(total_bbox_width / ANCHO_PROMEDIO_PALABRA)
        if num_palabras_estimado == 0 and total_bbox_width > 0:
            num_palabras_estimado = 1

    return {
        'tipo': 'texto' if num_componentes > 0 else 'vacío',
        'count_cc': num_componentes,
        'count_char_est': num_caracteres_estimado,
        'count_word_est': num_palabras_estimado,
        'stats': stats_filtrados_final
    }

# =========================================================================
# 4. FUNCIÓN DE VALIDACIÓN (RESULTADO: "OK" / "MAL" ÚNICAMENTE)
# =========================================================================
def validar_campo(campo_nombre, info_data, info_si=None, info_no=None):


    CC_NOMBRE_MIN = 9  # Mínimo para Nombre (asume 2 palabras y 25 chars)
    CC_EDAD_MIN = 3     # Mínimo para Edad (asume 2 o 3 dígitos)
    CC_MAIL_MIN = 31    # Mínimo para Mail (asume 'a@b.c' y longitud total)
    CC_LEGAJO_MIN = 8  # Mínimo para Legajo (asume 8 caracteres)
    CC_COM_MIN = 25     # Mínimo para Comentarios (al menos una palabra)
    CC_TOTAL_MAX = 70   # CC Máximo absoluto para cualquier campo de texto corto


    num_componentes = info_data['count_cc']
    num_palabras = info_data['count_word_est']

    num_caracteres_estimado = info_data['count_char_est']




    # 1. Validación de campos de texto (Basada en los requisitos)
    if not campo_nombre.startswith("Pregunta"):
        if campo_nombre == "Nombre y Apellido":

            if num_caracteres_estimado > CC_NOMBRE_MIN or num_palabras > 2:
                return "OK"
            return "MAL"

        elif campo_nombre == "Edad":
            # Requisito: 2 o 3 caracteres consecutivos.

            if num_caracteres_estimado <= CC_EDAD_MIN and num_caracteres_estimado >1:
                return "OK"
            return "MAL"

        elif campo_nombre == "Legajo":
            # Requisito: 8 caracteres en total, formando una única palabra.

            if num_componentes == CC_LEGAJO_MIN :
                return "OK"
            return "MAL"




        elif campo_nombre == "Mail":
            # Requisito: Contener una palabra y no más de 25 caracteres.

            if (num_caracteres_estimado > CC_MAIL_MIN and num_palabras > 1 ):
                return "OK"
            return "MAL"


        elif campo_nombre == "Comentarios":
            # Requisito: Contener al menos una palabra y no más de 25 caracteres.

            if num_componentes < CC_COM_MIN and num_palabras > 1:
                return "OK"
            return "MAL"

    elif campo_nombre.startswith("Pregunta"):

      # IMPORTANTE: Asumimos que estas variables contienen el conteo de CCs
      cc_si = info_si['count_cc']
      cc_no = info_no['count_cc']

      # --- 1. DEFINICIÓN DE MARCA VÁLIDA (SIMPLICIDAD) ---
      # Una marca solo es "válida" si tiene EXACTAMENTE 1 CC.
      # cc_si == 1 cubre el requisito de "único caracter".
      es_si_valido = cc_si == 1
      es_no_valido = cc_no == 1
      if cc_si >= 2 or cc_no >= 2:
        return f"MAL (Doble Marca Excesiva. CC_Si:{cc_si}, CC_No:{cc_no})"
      # La suma binaria (0, 1, o 2) indica el estado lógico
      suma_logica = es_si_valido + es_no_valido

      # --- 2. EVALUACIÓN LÓGICA (Exclusividad y Presencia) ---

      # Caso OK: Exclusivamente una de las dos es válida (suma_logica == 1)
      if suma_logica == 1:
        # Esto cubre: (Si=Válido y No=No Válido) O (Si=No Válido y No=Válido)
        return "OK"

      # Casos MAL

      # Caso MAL 1: Doble Marca (Suma logica == 2)
      elif suma_logica >= 2:
        # Ambas tienen 1 CC. Rechazada por ser DOBLE MARCA.
        return f"MAL (Doble Marca Válida. CC_Si:{cc_si}, CC_No:{cc_no})"

      # Caso MAL 2: Vacío (Suma logica == 0)
      elif suma_logica == 0:
        # Ninguna tiene 1 CC. Rechazada por VACÍO o porque la tinta es INVÁLIDA (Ej: 0 CCs, 2 CCs, 3 CCs).

        # Filtro adicional para tinta excesiva, por si la validación anterior no la capturó
        if cc_si >= 2 or cc_no >= 2:
            return f"MAL (Tinta Excesiva/No es único carácter. CC_Si:{cc_si}, CC_No:{cc_no})"

        # Si no es excesiva, es Vacío (0 CCs) o Ruido (ej: 0 CCs)
      return f"MAL (Vacío/Sin Marca de 1 CC. CC_Si:{cc_si}, CC_No:{cc_no})"

    # Caso por defecto, aunque la lógica suma_logica=0, 1, o 2 debería cubrir todo.
    return "MAL (Error de Lógica)"






# =========================================================================
# 5. CÓDIGO PRINCIPAL DE PROCESAMIENTO
# =========================================================================




def procesar_formulario(file_path):
    file_id = os.path.basename(file_path).split('_')[-1].split('.')[0]
    resultados = {'ID': file_id, 'Tipo': 'N/A', 'Validacion_Global': 'MAL', 'Error': 'OK'}

    # Inicialización de columnas extendidas
    for campo in CAMPO_NOMBRES:
        resultados[campo] = 'N/A'
        resultados[f"{campo}_CC"] = 0
        resultados[f"{campo}_Chars"] = 0
        resultados[f"{campo}_Words"] = 0

    img_color = cv2.imread(file_path)
    if img_color is None:
        resultados['Error'] = f"Error: No se pudo leer el archivo {file_path}"
        return resultados

    try:
        img_gray = cv2.cvtColor(img_color, cv2.COLOR_BGR2GRAY)
        celdas_coords = detectar_coordenadas_campos(img_gray)

        if file_id in ['01', '02','03']: tipo_form_id = 'A'
        elif file_id in ['04', '05']: tipo_form_id = 'B'
        else: tipo_form_id = 'C'
        resultados['Tipo'] = tipo_form_id
        is_global_ok = True

        coords_na = None

        print(f"\n--- Procesando Formulario {file_id} (Tipo {tipo_form_id}) ---")

        for i, campo_nombre in enumerate(CAMPO_NOMBRES):

            # Inicialización de info_data/si/no para el loop actual
            info_data = {'count_cc': 0, 'count_char_est': 0, 'count_word_est': 0}
            info_si = None
            info_no = None

            # ------------------------------------------------------------------
            # A. Lógica para PREGUNTAS (Pregunta 1, 2, 3)
            # ------------------------------------------------------------------
            if campo_nombre.startswith("Pregunta"):
                p_id = campo_nombre[-1]

                # 1. Obtener coordenadas de las opciones SI/NO
                coords_si = next((c[0] for c in celdas_coords if c[1] == f"P{p_id}_Si"), None)
                coords_no = next((c[0] for c in celdas_coords if c[1] == f"P{p_id}_No"), None)

                if coords_si is None or coords_no is None:
                    resultados[campo_nombre] = 'MAL (Celdas Si/No no Segmentadas)'
                    is_global_ok = False
                    continue

                # 2. Llamada para Opciones: Los nombres 'P1_Si' y 'P2_No' activan los filtros estrictos.
                info_si = extraer_contenido_celda(img_gray, coords_si, file_id, f"P{p_id}_Si")
                info_no = extraer_contenido_celda(img_gray, coords_no, file_id, f"P{p_id}_No")

                # 3. Validar: info_data se mantiene en cero para el campo principal.
                resultado = validar_campo(campo_nombre, info_data, info_si, info_no)

            # ------------------------------------------------------------------
            # B. Lógica para CAMPOS DE TEXTO (Nombre, Mail, Edad, Legajo, Comentarios)
            # ------------------------------------------------------------------
            else:
                coords_data = next((c[0] for c in celdas_coords if c[1] == campo_nombre), None)

                if coords_data is None:
                    resultados[campo_nombre] = 'MAL (No Segmentado)'
                    is_global_ok = False
                    continue

                if campo_nombre == "Nombre y Apellido":
                    coords_na = coords_data

                # Llamada para Texto: El nombre (ej. 'Mail') NO activa los filtros estrictos.
                info_data = extraer_contenido_celda(img_gray, coords_data, file_id, campo_nombre)

                resultado = validar_campo(campo_nombre, info_data)

            # --- CIERRE, ALMACENAMIENTO Y DEBUG ---

            # Almacenamiento de métricas (usa info_data para texto o el inicializado a cero para preguntas)
            resultados[f"{campo_nombre}_CC"] = info_data['count_cc']
            resultados[f"{campo_nombre}_Chars"] = info_data['count_char_est']
            resultados[f"{campo_nombre}_Words"] = info_data['count_word_est']

            resultados[campo_nombre] = resultado
            if resultado.startswith('MAL'):
                is_global_ok = False

            # Salida de impresión
            if campo_nombre.startswith("Pregunta"):
                cc_si = info_si['count_cc'] if info_si else 0
                cc_no = info_no['count_cc'] if info_no else 0
                print(f"  -> {campo_nombre}: {resultado} (Si CC:{cc_si}, No CC:{cc_no})")
            else:
                print(f"  -> {campo_nombre}: {resultado} (CC:{info_data['count_cc']})")
                #print(f"  -> {campo_nombre}: {resultado} (CC:{info_data['count_cc']}, Words:{info_data['count_word_est']})")

        resultados['Validacion_Global'] = 'OK' if is_global_ok else 'MAL'
        resultados['Coords_NA'] = coords_na
        resultados['File_Path'] = file_path
        return resultados

    except Exception as e:
        resultados['Validacion_Global'] = 'MAL'
        # Añade detalles de qué campo estaba procesando al momento del error, si es posible.
        resultados['Error'] = f"Excepción en procesamiento: {str(e)}"
        return resultados
# =========================================================================
# 6. EJECUCIÓN DEL SCRIPT
# =========================================================================
todos_los_resultados = []
nombre_apellido_data = {}

# La función generar_imagen_indicadora no está incluida, se usa solo para generar el reporte.
def generar_imagen_indicadora(todos_los_resultados, nombre_apellido_data):
    return "indicador_validacion_global.png" # Retorno mock

for file in ARCHIVOS_FORMULARIO:
    # Solo procesamos si el archivo existe
    if os.path.exists(file):
        resultados = procesar_formulario(file)
        todos_los_resultados.append(resultados)

        if resultados.get('Coords_NA'):
            nombre_apellido_data[resultados['ID']] = {
                'coords': resultados['Coords_NA'],
                'path': resultados['File_Path']
            }

        print(f"  -> VALIDACIÓN GLOBAL: {resultados.get('Validacion_Global', 'N/A')}")
        if resultados.get('Error', 'OK') != 'OK':
             print(f"  -> Detalle de Error: {resultados.get('Error', 'OK')}")
        print("-" * 50)
    else:
        print(f"❌ Archivo no encontrado: {file}. Se saltará el procesamiento.")

print("\n" + "="*50)
print("REPORTE B: Resultados por Tipo de Formulario")
print("="*50)
try:
    df_resultados = pd.DataFrame([res for res in todos_los_resultados if 'ID' in res]).set_index('ID')
    tipos_unicos = df_resultados['Tipo'].unique()
    for tipo in tipos_unicos:
        df_tipo = df_resultados[df_resultados['Tipo'] == tipo]
        num_total = len(df_tipo)
        num_ok = (df_tipo['Validacion_Global'] == 'OK').sum()
        print(f"\nTipo: {tipo} | Total: {num_total}")
        print(f"  OK: {num_ok}, MAL: {num_total - num_ok}")
except Exception as e:
    print(f"Error al generar el Reporte B: {e}")

print("\n" + "="*50)
print("CREACIÓN DE ARCHIVOS DE SALIDA")
print("="*50)
try:
    # La generación de la imagen requiere que la función esté implementada. Se usa el mock.
    output_img_name = generar_imagen_indicadora(todos_los_resultados, nombre_apellido_data)
    print(f"✅ Imagen indicadora (Requisito C): '{output_img_name}' (Mock) generada.")
except Exception as e:
    print(f"❌ Error al generar la imagen indicadora (Requisito C): {e}")

try:
    if 'df_resultados' in locals() and not df_resultados.empty:
        # Se filtran las columnas de métricas extendidas para el CSV final
        columnas_csv = ['ID', 'Tipo', 'Validacion_Global'] + CAMPO_NOMBRES
        df_csv = df_resultados.reset_index()[columnas_csv]
        df_csv.to_csv(CSV_OUTPUT, index=False)
        print(f"✅ Archivo CSV (Requisito D): '{CSV_OUTPUT}' generado.")
except Exception as e:
    print(f"❌ Error al generar el CSV: {e}")